# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SalesForce tests CI

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choose a browser
        options:
        - chrome
        - firefox

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npx playwright install
    - run: npm run test:${{ inputs.browser }}
      env:
        TESTUSERNAME: ${{ secrets.TESTUSERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        BASE_URL: ${{ vars.BASE_URL }}
        BROWSER: ${{ vars.BROWSER }}
        HEADLESS: ${{ vars.HEADLESS }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      if: ${{ always() }}
      with:
        name: Publish Report
        path: playwright-report
